name: CI CD pipeline
on:
    push: 
        branches: 
            -main
jobs:
    start: 
        runs-on: ubuntu-latest
        env:
            PORT: 5001
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm ci
            
            - name: Run app
              run: npm start